Tb 2.12 57 rebase+adapt
TrenchBoot/grub pull request #22
Opened 2024-08-07 11:06 UTC by BeataZdunczyk

2024-08-07 16:18 UTC, krystian-hebel requested changes
I know I said to not worry about MB2 too much, yet most of my comments are about it. It would be better to have one common branch if possible, and because we plan to upstream it, might as well be fixed now rather than later. (Another option would be to remove MB2 altogether from this branch and add it later, but that would unnecessarily double the effort)

2024-08-07 16:18 UTC, krystian-hebel commented on grub-core/loader/multiboot_elfxx.c
> +	    mld->align = GRUB_TXT_PMR_ALIGN;
These are for TXT only, AMD doesn't have such restrictions, neither does it use page tables. Still, `#ifndef GRUB_USE_MULTIBOOT2` part applies to both so it isn't simple change from `!= SLP_NONE` to `== SLP_INTEL_TXT`.

2024-08-07 16:18 UTC, krystian-hebel commented on grub-core/loader/multiboot_elfxx.c
> +      if (grub_slaunch_platform_type () != SLP_NONE)
Same as above.

2024-08-07 16:18 UTC, krystian-hebel commented on grub-core/loader/multiboot_mbi2.c
> +      if (grub_slaunch_platform_type () == SLP_INTEL_TXT)
```suggestion
      if (grub_slaunch_platform_type () != SLP_NONE)
```

2024-08-07 16:18 UTC, krystian-hebel commented on grub-core/loader/i386/skinit.c
> +                (unsigned) slparams->tpm_evt_log_size);
Event log is already allocated in https://github.com/TrenchBoot/grub/pull/22/files#diff-8c69f5f8f99bf5f4195720ea867e6e8fe273f9261ce151f58222e0d73b34c208R297, it isn't needed here. The only difference is that `grub_txt_init_tpm_event_log()` is called there instead of `grub_memset()` here, but it shouldn't be a problem, SKL clears the buffer anyway.

2024-08-07 16:18 UTC, krystian-hebel commented on grub-core/loader/multiboot_mbi2.c
> +  if (grub_slaunch_platform_type () == SLP_INTEL_TXT)
Together with change in skinit.c:

```suggestion
  if (grub_slaunch_platform_type () != SLP_NONE)
```

2024-08-07 16:18 UTC, krystian-hebel commented on grub-core/loader/multiboot_mbi2.c
> +      grub_txt_setup_mle_ptab (slparams);
```suggestion
      if (grub_slaunch_platform_type () == SLP_INTEL_TXT)
        grub_txt_setup_mle_ptab (slparams);
```

2024-08-07 16:18 UTC, krystian-hebel commented on grub-core/loader/multiboot_mbi2.c
> +    slparams->boot_params_addr = *target;
Not needed, done in `grub_multiboot2_prepare_slaunch()`.

2024-08-07 16:18 UTC, krystian-hebel commented on include/grub/i386/skinit.h
> +#ifndef ASM_FILE
Might as well drop it. I think this is a leftover from when `skinit` instruction was defined as a sequence of bytes because some compiler didn't have it implemented.

2024-08-07 16:18 UTC, krystian-hebel commented on include/grub/slr_table.h
> +/*
Please update this file to align with https://github.com/TrenchBoot/linux/blob/linux-sl-6.9/include/linux/slr_table.h, there are some differences in structure definitions, e.g. there is no `slr_entry_intel_info.txt_heap` here. If there are any changes to structures defined in SKL (it doesn't have Intel-specific structures), change https://github.com/TrenchBoot/secure-kernel-loader/pull/21 as well.

2024-08-08 14:54 UTC, SergiiDmytruk commented on grub-core/loader/i386/skinit.c
> +                (unsigned) slparams->tpm_evt_log_size);
https://github.com/TrenchBoot/grub/compare/58f381041fe9f418529a53abb339ce78f1d38924..ccf8d46f1529cbc011ecd0b0ad02957ef7e40c4b#diff-ee6e12de6eb52b720e2e6f3792ff7228232d905b280bef353649ae579b9a110e

2024-08-08 14:55 UTC, SergiiDmytruk commented on grub-core/loader/multiboot_elfxx.c
> +	    mld->align = GRUB_TXT_PMR_ALIGN;
https://github.com/TrenchBoot/grub/compare/58f381041fe9f418529a53abb339ce78f1d38924..ccf8d46f1529cbc011ecd0b0ad02957ef7e40c4b#diff-32e991c56790cec87f55280083791c5f9af329a33f9b67cc8998ac8da765c5d4R133-R156

2024-08-08 14:55 UTC, SergiiDmytruk commented on grub-core/loader/multiboot_elfxx.c
> +      if (grub_slaunch_platform_type () != SLP_NONE)
https://github.com/TrenchBoot/grub/compare/58f381041fe9f418529a53abb339ce78f1d38924..ccf8d46f1529cbc011ecd0b0ad02957ef7e40c4b#diff-32e991c56790cec87f55280083791c5f9af329a33f9b67cc8998ac8da765c5d4R183-R207

2024-08-08 14:56 UTC, SergiiDmytruk commented on grub-core/loader/multiboot_mbi2.c
> +      if (grub_slaunch_platform_type () == SLP_INTEL_TXT)
https://github.com/TrenchBoot/grub/compare/58f381041fe9f418529a53abb339ce78f1d38924..ccf8d46f1529cbc011ecd0b0ad02957ef7e40c4b#diff-285279252527f5bc911013189ac09a0880271f60dc8f28f28fe68c2f5d517c74R283-R286

2024-08-08 14:56 UTC, SergiiDmytruk commented on grub-core/loader/multiboot_mbi2.c
> +  if (grub_slaunch_platform_type () == SLP_INTEL_TXT)
https://github.com/TrenchBoot/grub/compare/58f381041fe9f418529a53abb339ce78f1d38924..ccf8d46f1529cbc011ecd0b0ad02957ef7e40c4b#diff-285279252527f5bc911013189ac09a0880271f60dc8f28f28fe68c2f5d517c74R402

2024-08-08 14:57 UTC, SergiiDmytruk commented on grub-core/loader/multiboot_mbi2.c
> +      grub_txt_setup_mle_ptab (slparams);
https://github.com/TrenchBoot/grub/compare/58f381041fe9f418529a53abb339ce78f1d38924..ccf8d46f1529cbc011ecd0b0ad02957ef7e40c4b#diff-285279252527f5bc911013189ac09a0880271f60dc8f28f28fe68c2f5d517c74R419-R428

2024-08-08 14:57 UTC, SergiiDmytruk commented on grub-core/loader/multiboot_mbi2.c
> +    slparams->boot_params_addr = *target;
https://github.com/TrenchBoot/grub/compare/58f381041fe9f418529a53abb339ce78f1d38924..ccf8d46f1529cbc011ecd0b0ad02957ef7e40c4b#diff-285279252527f5bc911013189ac09a0880271f60dc8f28f28fe68c2f5d517c74L761-L766

2024-08-08 14:57 UTC, SergiiDmytruk commented on include/grub/i386/skinit.h
> +#ifndef ASM_FILE
https://github.com/TrenchBoot/grub/compare/58f381041fe9f418529a53abb339ce78f1d38924..ccf8d46f1529cbc011ecd0b0ad02957ef7e40c4b#diff-5d70d6dc848c0abd171fd32c2f6b3817be988fe975f95d8de7469557a381a6c5

2024-08-08 15:08 UTC, SergiiDmytruk commented on include/grub/slr_table.h
> +/*
That was the only difference in structures.

https://github.com/TrenchBoot/grub/compare/ccf8d46f1529cbc011ecd0b0ad02957ef7e40c4b..0565379eb31b55eb17d3541b678eb82ae4290a87

2024-08-09 12:17 UTC, krystian-hebel approved these changes

2024-08-09 12:18 UTC, merged